### ISSUE TITLE
关于结节与血管问题

### ISSUE THREAD

**Issue by SCP-173-cool** [bzhou830/DiagnoseSystem#1]
您好，我想请教下，在影像方面，如何区分结节和血管

**Comment by bzhou830** [comment]
在断层影像上面，结节的形态和血管非常相似，因为可以从三维空间上进行考虑。在空间上血管是条状的结构，但是结节是类球状的结构。

**Comment by SCP-173-cool** [comment]
@bzhou830 感谢您的回复，这么说对于医生进行标记过程中，是需要看连续几张2D的片子然后进行标定是么？会通过3D可视化的方式来标定么？
